# Generated by Django 4.1.7 on 2023-05-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
