# Generated by Django 4.1.7 on 2023-05-04 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0005_remove_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_and_time_sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 5, 18, 32, 471360, tzinfo=datetime.timezone.utc)),
        ),
    ]
