# Generated by Django 4.1.7 on 2023-05-04 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0006_alter_message_date_and_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_and_time_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
