# Generated by Django 4.1.7 on 2023-04-18 03:16

from django.db import migrations, models
import profile_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet_post_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name=' Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=500)),
                ('profile_picture', models.ImageField(blank=True, default='', max_length=255, null=True, upload_to=profile_app.models.get_profile_image_filepath)),
                ('location', models.CharField(choices=[('FARGO', 'Fargo'), ('MINOT', 'Minot'), ('BISMARCK', 'Bismarck'), ('DICKINSON', 'Dickinson'), ('WILLISTON', 'Williston'), ('DEVILS_LAKE', 'Devils Lake')], default='FARGO', max_length=30)),
                ('liked_posts', models.ManyToManyField(blank=True, to='pet_post_app.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
