# Generated by Django 4.1.7 on 2023-04-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture_of_dog', models.ImageField(default='', upload_to='pet_post_app/post_pictures')),
                ('name', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('personality', models.CharField(choices=[('COUCH_POTATOE', 'Couch potatoe'), ('ENERGETIC', 'Energetic'), ('SOCIABLE', 'Sociable'), ('CUDDLY', 'Cuddly'), ('PLAYFUL', 'Playful'), ('PROTECTIVE', 'Protective')], default='CALM', max_length=40)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large')], default='MD', max_length=2)),
                ('description', models.CharField(max_length=500)),
                ('good_with_pets', models.BooleanField()),
                ('good_with_kids', models.BooleanField()),
                ('problems_and_disabilities', models.CharField(max_length=500)),
            ],
        ),
    ]
