# Generated by Django 4.1.7 on 2023-04-18 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
        ('pet_post_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_that_posted_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.profile'),
        ),
    ]
