# Generated by Django 4.1.7 on 2023-05-01 22:54

from django.db import migrations, models
import pet_post_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_post_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture_of_dog',
            field=models.ImageField(default='', upload_to=pet_post_app.models.get_profile_image_filepath),
        ),
    ]
